$schema: 'https://moonrepo.dev/schemas/tasks.json'

inheritedBy:
  toolchains: ['python', 'unstable_python']

fileGroups:
  sources:
    - '**/*.py'
  configs:
    - 'pyproject.toml'
    - 'uv.lock'

tasks:
  lint:
    command: 'python -m ruff check .'
    inputs:
      - '@group(sources)'
      - '@group(configs)'
    options:
      cache: false

  typecheck:
    command: 'python -m mypy .'
    inputs:
      - '@group(sources)'
      - '@group(configs)'
    options:
      cache: false

  test:
    command: 'python -m pytest'
    inputs:
      - '@group(sources)'
    env:
      GRPC_JWT_SECRET: 'ci-test-secret-at-least-32-chars!!'
    options:
      cache: false
